[package]
name = "joshgit777/omega"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["build"]
include = ["src/shared/Omega"]

descriptions = "NPC System based on character controllers and state machines"

[dependencies]
